### ISSUE TITLE
KeyError: "['IDfg'] not in index"

### ISSUE THREAD

**Issue by windowshopr** [baileymorton989/baseballforecaster#3] opened 2021-02-11 20:06 UTC
Hey, question for ya,

Ran the script using a previous date of `2019-07-12 00:00:00` to `2019-07-12 23:59:59` and ran into the error:

```
  File "main.py", line 192, in <module>
    current_stat_batter = filter_for_current_stats(current_batter_dict, batter_stats)
  File "main.py", line 188, in filter_for_current_stats
    current_dict.update({name:dictionary[name][stats]})
  File "C:\Users\Python37\lib\site-packages\pandas\core\frame.py", line 2908, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1, raise_missing=True)[1]
  File "C:\Users\Python37\lib\site-packages\pandas\core\indexing.py", line 1254, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis, raise_missing=raise_missing)
  File "C:\Users\Python37\lib\site-packages\pandas\core\indexing.py", line 1304, in _validate_read_indexer
    raise KeyError(f"{not_found} not in index")
KeyError: "['IDfg'] not in index"
```

Line 192 might not be super accurate as I've added some prints in the script, but it happens around the "filter_for_current_stats" function. Just wondering, should I be using this on past dates and run the risk of this column not being in the dictionary, or is this is a bug? Thanks! Looking forward to getting it workin!

**Comment by baileymorton989** [comment] 2021-02-11 20:22
Hey @windowshopr,

Thank you for raising this. I should specify that this is only for full year data at the moment, I.e., it will return the aggregated stats for a single season. As a result, you cannot run it for a single days worth of games and I meant to change that date formatting to make that clearer. I am going to make a quick change to provide some clarity so you simply just enter the desired year. 

I am hoping to return to working on this code to allow for more functionality, such as “drafting” the best set of players before each game.

**Comment by baileymorton989** [comment] 2021-02-11 20:27
Try running the script now by just entering years only, instead of an entire date. Should only take a few minutes, I am hoping to expand this into a small library in the near future.

**Comment by windowshopr** [comment] 2021-02-11 20:28
Will do, one moment...

**Comment by windowshopr** [comment] 2021-02-11 20:35
Hmm. Same issue. I tried using 2019 - 2019 and 2018 - 2019??

**Comment by windowshopr** [comment] 2021-02-11 20:41
Doesn't like this section:

```
  File "main.py", line 189, in <module>
    current_stat_batter = filter_for_current_stats(current_batter_dict, batter_stats)
  File "main.py", line 185, in filter_for_current_stats
    current_dict.update({name:dictionary[name][stats]})
```

**Comment by baileymorton989** [comment] 2021-02-11 20:50
> Hmm. Same issue. I tried using 2019 - 2019 and 2018 - 2019??

Are you just entering 2018 in the first box and 2019 in the second box? That worked for me.

**Comment by windowshopr** [comment] 2021-02-11 20:56
Hmmmm. Yes, that's what I'm inputting also. I also just downloaded the new script with the progress bar as well, same issue. It's like it's not pulling the IDfg from the site or something? Weird. I have to run out for an appointment here now, but maybe when I get home I'll keep digging! If you have any suggestions til then just let me know. Thanks! :D

**Comment by baileymorton989** [comment] 2021-02-11 22:32
Sounds good, let me know. Are you entering the years just plainly? Just typing in, for example, 2018 into the entry box, not ‘2018’? I will need to dig through the script to see what the issue is.

**Comment by windowshopr** [comment] 2021-02-12 02:19
Hey,

Yeah, same issue. I'm just entering 2018 in the first textbox, and 2019 in the second. I've narrowed it down to this:

```
Traceback (most recent call last):
  File "main.py", line 192, in <module>
    current_stat_batter = filter_for_current_stats(current_batter_dict, batter_stats)
  File "main.py", line 188, in filter_for_current_stats
    current_dict.update({name:dictionary[name][stats]})
```

I see that `batter_stats` is defined in a list on line 180, but it looks like the stat `IDfg` isn't in the `current_batter_dict`. So I'm currently tracing it back up to line 105 to inpect the `seasons_dict_batter` to check out what columns that returns. My guess is IDfg is called something else, or not in there, or something silly like that. I'll report what I find!

**Comment by windowshopr** [comment] 2021-02-12 02:42
Yeah so I basically just threw this into the `make_seasons_dicts` function:

```
    batter_df = pyb.batting_stats(2018, qual = False)
    batter_df.to_csv("./test-2018.csv")
    
    batter_df = pyb.batting_stats(2019, qual = False)
    batter_df.to_csv("./test-2019.csv")
```

just so I could inspect the dataframes first, and I don't see any IDfg column names in there, so my guess is it's trying to reference a column that isn't in the dict, but how it's working for you and not me is baffling lol

**Comment by baileymorton989** [comment] 2021-02-12 02:54
Definitely still a baffled as you said, since it's working for me. Maybe its the version of pybaseball that you're using it?

Using the sample example, I printed out the columns for `season_dict_batter` and `seasons_dict_pitcher` and you can see that `IDfg ` is listed in both:

```
seasons_dict_batter['2018'].columns
Out[3]: 
Index(['IDfg', 'Season', 'Name', 'Team', 'Age', 'G', 'AB', 'PA', 'H', '1B',
       ...
       'Med%+', 'Hard%+', 'EV', 'LA', 'Barrels', 'Barrel%', 'maxEV', 'HardHit',
       'HardHit%', 'Events'],
      dtype='object', length=314)

seasons_dict_pitcher['2018'].columns
Out[4]: 
Index(['IDfg', 'Season', 'Name', 'Team', 'Age', 'W', 'L', 'WAR', 'ERA', 'G',
       ...
       'Med%+', 'Hard%+', 'EV', 'LA', 'Barrels', 'Barrel%', 'maxEV', 'HardHit',
       'HardHit%', 'Events'],
      dtype='object', length=330)
```

**Comment by windowshopr** [comment] 2021-02-12 03:06
I just updated my pybaseball to try that, as there was an update available, and now I'm getting connection attempt failed as I probably have exceeded my request limit :') I'll try again tomorrow as it's getting late where I am, else I'll just turn my VPN so I can test and get back to ya!

**Comment by baileymorton989** [comment] 2021-02-12 03:07
Sounds good, that might be the fix as I know they released an updated
version recently. Keep me posted!

**Comment by baileymorton989** [comment] 2021-02-17 02:57
Were you ever able to get the script running?

**Comment by windowshopr** [comment] 2021-02-17 03:27
Oh god, I swear I posted a response here, but for some reason it's not here? Maybe cuz I posted from my phone or something, I dunno. 

Yes, sorry for the delay here, I did get it working by updating my PyBaseball to the latest version. Works great! Takes a while to run of course, but there's lots of data to get through so it's understandable. Great work! And thanks for the help!!!

**Comment by baileymorton989** [comment] 2021-02-17 03:29
Good to hear! I will be making some updates to the repo soon, especially to handle single game forecasts. I will go ahead and close this issue.

**Closed by baileymorton989** 2021-02-17 03:29 UTC

**Comment by windowshopr** [comment] 2021-02-17 03:34
Lookin' forward to it! :D
